name: multivender_ecommerce_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
##UI
  cupertino_icons:
##State Management
  provider:
##Futures Reflections
  flutter_spinkit:
  flushbar:
##Firebase
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Light.ttf

